<?php

require_once 'conexionCancer.php'; 

//  variables de formulario 

//$fecha1 = $_POST['fecha1']; 
//$fecha2 = $_POST['fecha2']; 

//if(isset($_POST['generar_reporte']))
//{    
    // nombre del archivo 
    header('Content-Type:text/csv; charset = latin1'); 
    header('Content-Disposition: attachment; filename="reportecancer.csv"'); 

    //salida del archivo function de fopen w de write  
    $salida = fopen('php://output', 'W'); 

    //columnas del archivo , llamar a la funcion fputcsv
    fputcsv($salida, array(
        'ID',
        'Nombre completo', 
        'CURP',
        'Edad',
        'Sexo',
        'Poblacion indigena',
        'Raza',
        'Discapacidad',
        'Escolaridad',
        'Fecha nacimiento',
        'Estado',
        'Municipio',
        'Abandono paciente',
        'Referenciado',
        'Unidad referencia',
        'Clues de la unidad',
        'Antecedentes cancer',
        'talla',
        'peso',
        'imc',
        'menarca',
        'ultima mestruacion',
        'cuenta con',
        'gestas',
        'parto',
        'aborto',
        'cesarea',
        'embarazada',
        'f.p.p',
        'terapia reemplado hormonal',
        'lactancia',
        'tiempo lactancia',
        'Fecha atencion inicial',
        'BRADS referencia',
        'BRADS HRAEI',
        'Lateralidad',
        'Estadio clinico',
        'Etapa clinica',
        'Tamaño tumoral',
        'Compromiso linfatico nodal',
        'Metastasis',
        'Calidad de vida ECOG',
        'Matectomia extrainstitucional',
        'lateralidad mastectomia extrainstitucional',
        'Fecha mastectomia extrainstitucional',
        'DX histopatologico MMD',
        'Fecha DX histopatologico MMD',
        'Nottinghan MMD',
        'ESCALA SBR (SCARLET-BLOOM-RICHARDSON) MMD',
        'DX histopatologico MMI',
        'Fecha DX histopatologico MMI',
        'Nottinghan MMI',
        'ESCALA SBR (SCARLET-BLOOM-RICHARDSON) MMI',
        'Receptores de estrogenos (RE) MMD',
        'Receptores de progesterona (RP) MMD',
        'KI-67 MMD',
        'P 53 MMD',
        'Triple negativo MMD',
        'Aplico PDL MMD',
        'PDL MMD',
        'Oncogen HER2 MMD',
        'FISH MMD',
        'Receptores de estrogenos (RE) MMD',
        'Receptores de progesterona (RP) MMD',
        'KI-67 MMD',
        'P 53 MMD',
        'Triple negativo MMD',
        'Aplico PDL MMD',
        'PDL MMD',
        'Oncogen HER2 MMD',
        'FISH MMD',
        'Luminal A MMD',
        'Luminal B MMD',
        'Enriquecido HER 2 MMD',
        'Basal MMD',
        'Luminal A MMI',
        'Luminal B MMI',
        'Enriquecido HER 2 MMI',
        'Basal MMI',
        'Quirurgico',
        'Lateralidad',
        'Tipo mastectomia',
        'Fecha',
        'Tipo ganglionar',
        'Fecha',
        'Aplico quimioterapia',
        'Fecha aplico quimioterpaia',
        '1ra linea QT',
        'Ciclos 1ra linea QT',
        '2da linea QT',
        'Ciclos 2da linea QT',
        'Antraciclinas',
        'Momento de la QT',
        'Hormonoterapia',
        'Tipo hormonoterapia',
        'Momento hormonoterapia',
        'Her 2++',
        'Esquema her 2',
        'Triple negativo',
        'Esquema triple negativo',
        'Hormonosensible',
        'Esquema hormonosensible',
        'Tipo tratamiento',
        'Completo quimio',
        'Causa quimio incompleta',
        'Fecha de evento adverso',
        'Fecha progresion',
        'Fecha recurrencia',
        'Fecha fallecio',
        'Causa fallecio',
        'Especifique',
        'Aplico radioterapia',
        'Tipo de radioterapia',
        'Fecha de inicio',
        'Numero de sesiones',
        'Defuncion',
        'Fecha defuncion',
        'Causa defuncion'


    )); 


    $QueryConsulta= $conexion2->query("SELECT DISTINCT dato_usuario.id,dato_usuario.curp,dato_usuario.nombrecompleto,dato_usuario.poblacionindigena,dato_usuario.escolaridad,date_format(dato_usuario.fechanacimiento, '%d-%m-%Y') as fechanacimiento,dato_usuario.edad,dato_usuario.sexo,dato_usuario.discapacidad,dato_usuario.raza,dato_usuario.estado,dato_usuario.municipio, CASE WHEN dato_usuario.abandonopaciente = 1 THEN 'Paciente abandono' ELSE 'sin abandono' END as abandonopaciente,
unidadreferenciado.clues,unidadreferenciado.referenciado,cancerpaciente.descripcioncancer,t_estado.estado,t_municipio.municipio,hospitales.Unidad,signosvitales.talla, signosvitales.peso, signosvitales.imc, 
antecedentesgineco.menarca, date_format(antecedentesgineco.ultimamestruacion, '%d-%m-%Y') as ultimamestruacion, antecedentesgineco.cuentacon, antecedentesgineco.gestas, antecedentesgineco.parto, antecedentesgineco.aborto, 
antecedentesgineco.cesarea, antecedentesgineco.embarazada,date_format(antecedentesgineco.fpp, '%d-%m-%Y') as fpp, antecedentesgineco.terapiareemplazohormonal, antecedentesgineco.lactancia, antecedentesgineco.tiempolactancia,
date_format(atencionclinica.fechaatencioninicial, '%d-%m-%Y') as fechaatencioninicial,
atencionclinica.biradsreferencia,atencionclinica.biradshraei,atencionclinica.lateralidadmama,atencionclinica.estadioclinico,atencionclinica.etapaclinica,atencionclinica.tamaniotumoral,
atencionclinica.compromisolenfatico,atencionclinica.metastasis,atencionclinica.calidaddevidaecog,atencionclinica.mastectoextrainstituto,atencionclinica.lateralidadmastectoextrainstituto,date_format(atencionclinica.fechamastectoextrainstituto, '%d-%m-%Y') as fechamastectoextrainstituto,
histopatologia.dxhistopatologico,date_format(histopatologia.fechadxhistopatologico, '%d-%m-%Y') as fechadxhistopatologico,histopatologia.nottingham,histopatologia.escalasbr,
histopatologiaizquierda.dxhistopatologicoiz,date_format(histopatologiaizquierda.fechadxhistopatologicoiz, '%d-%m-%Y') as fechadxhistopatologicoiz, histopatologiaizquierda.nottinghamiz,histopatologiaizquierda.escalasbriz,
inmunohistoquimica.*,
inmunohistoquimicaiz.*,
molecular.*,
molecularizquierda.*,
quirurgico.realizoquirurgico,quirurgico.lateralidad,
mastecto_gaglionar.tipomastecto,mastecto_gaglionar.fecha_mastecto,mastecto_gaglionar.tipoganglionar,mastecto_gaglionar.fechatipogaglionar,
quimioterapia.aplicoquimio,date_format(quimioterapia.fechainicio, '%d-%m-%Y') as fechainicio,quimioterapia.primeralinea,quimioterapia.ciclosprimerlineaqt,quimioterapia.segundalinea,quimioterapia.ciclossegundalineaqt,quimioterapia.antraciclinas,quimioterapia.momentodelaqt,quimioterapia.hormonoterapia,quimioterapia.tipohormonoterapia,quimioterapia.momentohormonoterapia,
quimioterapia.her2,quimioterapia.esquemaher2,quimioterapia.triplenegativo,quimioterapia.esquematrilpenegativo,quimioterapia.hormonosensible,quimioterapia.esquemahormonosensible,quimioterapia.tipotratamiento,quimioterapia.completoquimio,quimioterapia.causaqtincompleta,date_format(quimioterapia.fechaeventoadverso, '%d-%m-%Y') as fechaeventoadverso,date_format(quimioterapia.fechaprogresion, '%d-%m-%Y') as fechaprogresion,
date_format(quimioterapia.fecharecurrencia, '%d-%m-%Y') as fecharecurrencia,date_format(quimioterapia.fechafallecio, '%d-%m-%Y') as fechafallecio,quimioterapia.causafallecio,quimioterapia.especifique,
radioterapia.aplicoradio,radioterapia.decripcionradio,radioterapia.fecharadio,radioterapia.numerodesesiones,
defencionpaciente.defuncion,date_format(defencionpaciente.fechadefuncion, '%d-%m-%Y') as fechadefuncion,defencionpaciente.causadefuncion
FROM dato_usuario
left outer join cancerpaciente on cancerpaciente.id_paciente = dato_usuario.id
left outer join unidadreferenciado on unidadreferenciado.id_paciente = dato_usuario.id
left outer join hospitales on hospitales.Clues = unidadreferenciado.clues
left outer join t_estado on t_estado.id_estado = dato_usuario.estado
left outer join t_municipio on t_municipio.id_municipio = dato_usuario.municipio 
left outer join signosvitales on signosvitales.id_paciente = dato_usuario.id
left outer join antecedentesgineco on antecedentesgineco.id_paciente = dato_usuario.id
left outer join atencionclinica on atencionclinica.id_usuario = dato_usuario.id
left outer join histopatologia on histopatologia.id_usuario = dato_usuario.id
left outer join histopatologiaizquierda on histopatologiaizquierda.id_paciente = dato_usuario.id
left outer join inmunohistoquimica on inmunohistoquimica.id_usuario = dato_usuario.id
left outer join inmunohistoquimicaiz on inmunohistoquimicaiz.id_usuario = dato_usuario.id
left outer join molecular on molecular.id_paciente = dato_usuario.id
left outer join molecularizquierda on molecularizquierda.id_paciente = dato_usuario.id
left outer join quirurgico on quirurgico.id_paciente = dato_usuario.id
left outer join mastecto_gaglionar on mastecto_gaglionar.id_paciente = dato_usuario.id
left outer join quimioterapia on quimioterapia.id_paciente = dato_usuario.id
left outer join radioterapia on radioterapia.id_paciente = dato_usuario.id
left outer join defencionpaciente on defencionpaciente.id_paciente = dato_usuario.id"); 
    while($filaR=$QueryConsulta->fetch_assoc())
        
    fputcsv($salida, array(
                        $filaR['id'],
                        $filaR['nombrecompleto'],
                        $filaR['curp'],
                        $filaR['edad'],
                        $filaR['sexo'],
                        $filaR['poblacionindigena'],
                        $filaR['raza'],
                        $filaR['discapacidad'],
                        $filaR['escolaridad'],
                        $filaR['fechanacimiento'],
                        $filaR['estado'],
                        $filaR['municipio'],
                        $filaR['abandonopaciente'],
                        $filaR['referenciado'],
                        $filaR['Unidad'],
                        $filaR['clues'],
                        $filaR['descripcioncancer'],
                        $filaR['talla'],
                        $filaR['peso'],
                        $filaR['imc'],
                        $filaR['menarca'],
                        $filaR['ultimamestruacion'],
                        $filaR['cuentacon'],
                        $filaR['gestas'],
                        $filaR['parto'],
                        $filaR['aborto'],
                        $filaR['cesarea'],
                        $filaR['embarazada'],
                        $filaR['fpp'],
                        $filaR['terapiareemplazohormonal'],
                        $filaR['lactancia'],
                        $filaR['tiempolactancia'],
                        $filaR['fechaatencioninicial'],
                        $filaR['biradsreferencia'],
                        $filaR['biradshraei'],
                        $filaR['lateralidadmama'],
                        $filaR['estadioclinico'],
                        $filaR['etapaclinica'],
                        $filaR['tamaniotumoral'],
                        $filaR['compromisolenfatico'],
                        $filaR['metastasis'],
                        $filaR['calidaddevidaecog'],
                        $filaR['mastectoextrainstituto'],
                        $filaR['lateralidadmastectoextrainstituto'],
                        $filaR['fechamastectoextrainstituto'],
                        $filaR['dxhistopatologico'],
                        $filaR['fechadxhistopatologico'],
                        $filaR['nottingham'],
                        $filaR['escalasbr'],
                        $filaR['dxhistopatologicoiz'],
                        $filaR['fechadxhistopatologicoiz'],
                        $filaR['nottinghamiz'],
                        $filaR['escalasbriz'],
                        $filaR['receptoresestrogenos'],
                        $filaR['receptoresprogesterona'],
                        $filaR['ki67'],
                        $filaR['p53'],
                        $filaR['triplenegativo'],
                        $filaR['aplicopdl'],
                        $filaR['descripcionpdl'],
                        $filaR['oncogenher2'],
                        $filaR['fish'],
                        $filaR['receptoresestrogenosiz'],
                        $filaR['receptoresprogesteronaiz'],
                        $filaR['ki67iz'],
                        $filaR['p53iz'],
                        $filaR['triplenegativoiz'],
                        $filaR['aplicopdliz'],
                        $filaR['descripcionpdliz'],
                        $filaR['oncogenher2iz'],
                        $filaR['fishiz'],
                        $filaR['luminala'],
                        $filaR['luminalb'],
                        $filaR['enriquecidoher2'],
                        $filaR['basal'],
                        $filaR['luminalaiz'],
                        $filaR['luminalbiz'],
                        $filaR['enriquecidoher2iz'],
                        $filaR['basaliz'],
                        $filaR['realizoquirurgico'],
                        $filaR['lateralidad'],
                        $filaR['tipomastecto'],
                        $filaR['fecha_mastecto'],
                        $filaR['tipoganglionar'],
                        $filaR['fechatipogaglionar'],
                        $filaR['aplicoquimio'],
                        $filaR['fechainicio'],
                        $filaR['primeralinea'],
                        $filaR['ciclosprimerlineaqt'],
                        $filaR['segundalinea'],
                        $filaR['ciclossegundalineaqt'],
                        $filaR['antraciclinas'],
                        $filaR['momentodelaqt'],
                        $filaR['hormonoterapia'],
                        $filaR['tipohormonoterapia'],
                        $filaR['momentohormonoterapia'],
                        $filaR['her2'],
                        $filaR['esquemaher2'],
                        $filaR['triplenegativo'],
                        $filaR['esquematrilpenegativo'],
                        $filaR['hormonosensible'],
                        $filaR['esquemahormonosensible'],
                        $filaR['tipotratamiento'],
                        $filaR['completoquimio'],
                        $filaR['causaqtincompleta'],
                        $filaR['fechaeventoadverso'],
                        $filaR['fechaprogresion'],
                        $filaR['fecharecurrencia'],
                        $filaR['fechafallecio'],
                        $filaR['causafallecio'],
                        $filaR['especifique'],
                        $filaR['aplicoradio'],
                        $filaR['decripcionradio'],
                        $filaR['fecharadio'],
                        $filaR['numerodesesiones'],
                        $filaR['defuncion'],
                        $filaR['fechadefuncion'],
                        $filaR['causadefuncion']
                    ));

//}

?>